import AntdProvider from "@/providers/AntdProvider";
import type { Metadata } from "next";
import "./globals.scss";
export const metadata: Metadata = {
  title: "Deepcare Patient Portal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`g-body`}>
        <AntdProvider>{children}</AntdProvider>
      </body>
    </html>
  );
}
